const inspectionMeasurementsBCModel = {


    "2_1_2_b":{
        avg:0,
        result:false
    },    
    "2_2":{
        avg:0,
        result:false
    },
    "2_3_2":{
        avg:0,
        result:false
    },
    "4_3_1":{
        avg:0,
        result:false
    },
    "5_2_3":{
        values:[0,0,0],
        result:false
    },
    "5_2_4":{
        avg:0,
        result:false
    },
    "5_3":{
        values:[{
                    p1:0,
                    q:0
                },{
                    p1:0,
                    q:0
                },{
                    p1:0,
                    q:0
                }],
        result:false
    },
    "5_4_1":{
        avg:0,
        result:false
    },
    "5_4_2":{
        avg:0,
        result:false
    },
    "8_1_2":{
        values:[0,0],
        result:false
    },
    "8_3_1":{
        values:[],
        result:true
    },
    "8_3_2":{
        values:[],
        result:true
    },
    "8_4_1":{
        low:0,
        high:0,
        result:false
    },
    "8_4_2":{
        value:0,
        result:false
    },
    "8_8":{
        values:[],
        result:false
    },
    "8_9":{
        values:[],
        result:false
    },
    "9_3_2_a":{
        values:[],
        result:false
    },
    "9_3_2_b":{
        result:false
    }
}


export default inspectionMeasurementsBCModel;