const inspectionTechnicalReportMVModel = {
    "1_1":{
        result:true,
        notes:""
    },
    "1_2_1":{
        result:true,
        notes:""
    },
    "1_2_2":{
        result:true,
        notes:""
    },
    "1_3":{
        result:true,
        notes:""
    },
    "2_1_1_a":{
        result:true,
        notes:""
    },
    "2_1_2_a":{
        result:true,
        notes:""
    },
    "2_1_2_b":{
        result:true,
        notes:""
    },
    "2_2":{
        result:true,
        notes:""
    },

    "2_3_1":{
        result:true,
        notes:""
    },
    "3_1":{
        result:true,
        notes:""
    },
    "3_2":{
        result:true,
        notes:""
    },
    "4_1_1":{
        result:true,
        notes:""
    },
    "4_1_2":{
        result:true,
        notes:""
    },
    "4_2":{
        result:true,
        notes:""
    },
    "4_3_1":{
        result:true,
        notes:""
    },
    "4_3_2":{
        result:true,
        notes:""
    },
    "4_4":{
        result:true,
        notes:""
    },
    "4_5":{
        result:true,
        notes:""
    },
    "4_6":{
        result:true,
        notes:""
    },
    "4_7":{
        result:true,
        notes:""
    },
    "4_8":{
        result:true,
        notes:""
    },
    "4_9":{
        result:true,
        notes:""
    },
    "5_1_1":{
        result:true,
        notes:""
    },
    "5_1_2":{
        result:true,
        notes:""
    },
    "5_1_3":{
        result:true,
        notes:""
    },
    "5_1_4":{
        result:true,
        notes:""
    },
    "5_2_1":{
        result:true,
        notes:""
    },
    "5_2_2":{
        result:true,
        notes:""
    },
    "5_2_3":{
        result:true,
        notes:""
    },
    "5_2_5":{
        result:true,
        notes:""
    },
    "5_5_1":{
        result:true,
        notes:""
    },
    "6_1":{
        result:true,
        notes:""
    },
    "6_2":{
        result:true,
        notes:""
    },
    "7_1_1":{
        result:true,
        notes:""
    },
    "7_1_2":{
        result:true,
        notes:""
    },
    "7_1_3":{
        result:true,
        notes:""
    },
    "7_1_4":{
        result:true,
        notes:""
    },
    "7_2":{
        result:true,
        notes:""
    },
    "7_3":{
        result:true,
        notes:""
    },
    "8_1":{
        result:true,
        notes:""
    },
    "8_2_1_a":{
        result:true,
        notes:""
    },
    "8_2_2_a":{
        result:true,
        notes:""
    },
    "8_2_2_d":{
        result:true,
        notes:""
    },
    "8_2_3":{
        result:true,
        notes:""
    },
    "8_2_4":{
        result:true,
        notes:""
    },
    "8_3_1":{
        result:true,
        notes:""
    },
    "8_3_2":{
        result:true,
        notes:""
    },
    "8_3_3":{
        result:true,
        notes:""
    },
    "8_4_1_a":{
        result:true,
        notes:""
    },
    "8_4_1_b":{
        result:true,
        notes:""
    },
    "8_4_1_c":{
        result:true,
        notes:""
    },
    "8_4_2":{
        result:true,
        notes:""
    },
    "9_1":{
        result:true,
        notes:""
    },
    "9_2":{
        result:true,
        notes:""
    },
    "10_1":{
        result:true,
        notes:""
    },
    "11_1":{
        result:true,
        notes:""
    },
    "12_1":{
        result:true,
        notes:""
    }
}


export default inspectionTechnicalReportMVModel;